### ISSUE TITLE
initThreadPool freezes when compiling with -C lto flag

### ISSUE THREAD

**Issue by alordash** [GoogleChromeLabs/wasm-bindgen-rayon#27]
I used default example without bundlers.
lib.rs:
```rust
use wasm_bindgen::prelude::*;
use rayon::prelude::*;
pub use wasm_bindgen_rayon::init_thread_pool;

#[wasm_bindgen]
pub fn sum(numbers: &[i32]) -> i32 {
    numbers.par_iter().sum()
}
```
index.html:
```html
<!DOCTYPE html>
<body>
    <script type="module">
        new Worker('worker.js', { type: 'module' });
    </script>
</body>
```
worker.js:
```js
import init, { sum, initThreadPool } from "./pkg/test.js";
console.log(`Worker created`);
init().then(_ => {
    console.log(`Initialized wasm`);
    initThreadPool(navigator.hardwareConcurrency).then(_ => {
        console.log(`Initialized thread pool`);
        let result = sum(new Int32Array([1, 2, 3]))
        console.log(result)
    })
})
```
Cargo.toml:
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
wasm-bindgen = "0.2.74"
rayon = "1.5"
```
Without `lto = true` everything works fine. However when I compile with `lto = true`, function `initThreadPool` freezes.
Output without link time optimization:
![Ok](https://user-images.githubusercontent.com/54469554/167181717-50a703af-5336-4e9e-9e1d-0ce4126a2347.jpg)
Output with link time optimization:
![Frozen](https://user-images.githubusercontent.com/54469554/167181409-b8a34691-fe88-4950-963a-cab2f3c3d175.jpg)
