### ISSUE TITLE
Relative import path in workerHelpers.js is wrong?

### ISSUE THREAD

**Issue by josephrocca** [GoogleChromeLabs/wasm-bindgen-rayon#3]
I've got the following minimal project set up:

## Cargo.toml
```toml
[package]
name = "rayon-test"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-rayon = "1.0"
rayon = "1.5"
console_error_panic_hook = "0.1.6"
```

## lib.rs
```rs
use wasm_bindgen::prelude::*;
use rayon::prelude::*;
use console_error_panic_hook;
pub use wasm_bindgen_rayon::init_thread_pool;

#[wasm_bindgen]
pub fn sum_of_squares(input: Vec<i32>) -> i32 {
    console_error_panic_hook::set_once();
    input.par_iter().map(|&i| i * i).sum()
}
```

## index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>rayon test</title>
  </head>
  <body>
    <script type="module">
      import init, {initThreadPool, sum_of_squares} from "/rayon_test.js";
      await init();
      await initThreadPool(2);
      console.log(sum_of_squares([1,2,3]));
      </script>
  </body>
</html>
```
But I got an "invalid mime type" error at this module import line in `workerHelpers.js`:
```js
const pkg = await import('../../..');
```
I changed it to this:
```js
const pkg = await import('../../../rayon_test.js');
```
and now it works fine. Not exactly sure what went wrong there, and whether it was my fault, but reporting in case this is a bug.

Thanks!
