### ISSUE TITLE
Unit testing with #[wasm_bindgen_test]

### ISSUE THREAD

**Issue by ZhaoXiangXML** [GoogleChromeLabs/wasm-bindgen-rayon#30]
I'm trying to use `wasm-bindgen-rayon` in unit tests by `wasm-bindgen-test`, here is an demo project:

src/lib.rs
```rust
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};
use wasm_bindgen::prelude::*;

#[macro_export]
macro_rules! log {
    ($($arg:tt)*) => (
        web_sys::console::log_1(&format_args!($($arg)*).to_string().into())
    )
}

#[wasm_bindgen]
pub fn sum(numbers: &[i32]) -> i32 {
    numbers.par_iter().sum()
}

mod test {
    use super::*;
    use wasm_bindgen_futures::JsFuture;
    use wasm_bindgen_rayon::init_thread_pool;
    use wasm_bindgen_test::*;
    wasm_bindgen_test_configure!(run_in_browser);

    #[wasm_bindgen_test]
    async fn test() {
        log!("init thread pool");
        let _ = JsFuture::from(init_thread_pool(
            web_sys::window()
                .unwrap()
                .navigator()
                .hardware_concurrency() as usize,
        )).await;
        log!("after init thread pool");
        let nums: Vec<i32> = vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
        let sum = sum(&nums);
        assert_eq!(sum, 55);
    }
}

```

Cargo.toml:
```toml
[package]
name = "wasm-bindgen-rayon-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.81"
wasm-bindgen-test = "0.3.13"
rayon = "1.5"
wasm-bindgen-rayon = { version = "1.0" }
wasm-bindgen-futures = "0.4.30"

[dependencies.web-sys]
version = "*"
features = ["console", "Window", "Navigator"]
```

Then I ran the test with:
```bash
wasm-pack test --chrome --headless
```

and I got the following output:
```
    log output:
        init thread pool
        after init thread pool

    error output:
        panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Error { kind: Unsupported, message: "operation not supported on this platform" }) }', C:\SDK\rust\cargo\registry\src\github.com-1ecc6299db9ec823\rayon-core-1.9.3\src\registry.rs:170:10
```

I've add some logs in `wasm-bindgen-rayon`, it appears the callback in `waitForMsgType` was never called.

I'd like to know how can I fix this issue. Thank you.
